name: Release Pre Versions
on:
  push:
    branches:
      - release/**
    paths:
      - '**/ts'
      - '**/yml'
jobs:
  publishPreRelease:
    name: PreRelease Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "info@smartface.io"
      - name: Tag and Publish
        uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: ${{ github.ref_name }}
          split-by: '/'
      - run: |
          yarn version --prerelease --preid ${{ steps.split.outputs._1 }}
          npm run deploy:${{ steps.split.outputs._1 }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
      - name: Push New Version
        run: |
          git push
          git push --tags
  buildAndPushToDockerHub:
    runs-on: ubuntu-latest
    needs: [publishPreRelease]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git checkout HEAD^

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: echo version
        run: echo "${{ steps.package-version.outputs.current-version}}"

      - name: is this cycle alpha
        if: contains(steps.package-version.outputs.current-version, 'alpha')
        run: echo "RELEASE_CYCLE=alpha" >> $GITHUB_ENV

      - name: is this cycle beta
        if: contains(steps.package-version.outputs.current-version, 'beta')
        run: echo "RELEASE_CYCLE=beta" >> $GITHUB_ENV

      - name: is this cycle release
        if: true && !contains(steps.package-version.outputs.current-version, 'beta') && !contains(steps.package-version.outputs.current-version, 'alpha')
        run: echo "RELEASE_CYCLE=release" >> $GITHUB_ENV

      - name: echo release cycle
        run: echo "$RELEASE_CYCLE"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ref:${{env.RELEASE_CYCLE}}

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/ref:${{env.RELEASE_CYCLE}}
          run: |
            echo ${{ steps.docker_build.outputs.digest }}
    outputs:
      RELEASE_CYCLE: ${{env.RELEASE_CYCLE}}
  applyChanges:
    runs-on: ubuntu-latest
    needs: [buildAndPushToDockerHub]
    steps:
    - name: Execute Upgrade Command on Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ${{ secrets.SERVER_DOC_HELM_PATH }}
          echo ${{ secrets.SERVER_PASSWORD}} | ${{ secrets.SERVER_DOC_UPDATE_COMMAND }} ${{ secrets.SERVER_DOC_DEPLOYMENT_PREFIX }}-${{needs.buildAndPushToDockerHub.outputs.RELEASE_CYCLE}}
